In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
dataset = pd.read_csv(r"E:\project\chronickidneydisease.csv")

In [3]:
dataset.head()

id   age    bp     sg   al   su     rbc        pc         pcc          ba  \
0   0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent  notpresent   
1   1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent  notpresent   
2   2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  notpresent   
3   3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  notpresent   
4   4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  notpresent   

   ...  pcv    wc   rc  htn   dm  cad appet   pe  ane classification  
0  ...   44  7800  5.2  yes  yes   no  good   no   no            ckd  
1  ...   38  6000  NaN   no   no   no  good   no   no            ckd  
2  ...   31  7500  NaN   no  yes   no  poor   no  yes            ckd  
3  ...   32  6700  3.9  yes   no   no  poor  yes  yes            ckd  
4  ...   35  7300  4.6   no   no   no  good   no   no            ckd  

[5 rows x 26 columns]

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
id                400 non-null int64
age               391 non-null float64
bp                388 non-null float64
sg                353 non-null float64
al                354 non-null float64
su                351 non-null float64
rbc               248 non-null object
pc                335 non-null object
pcc               396 non-null object
ba                396 non-null object
bgr               356 non-null float64
bu                381 non-null float64
sc                383 non-null float64
sod               313 non-null float64
pot               312 non-null float64
hemo              348 non-null float64
pcv               330 non-null object
wc                295 non-null object
rc                270 non-null object
htn               398 non-null object
dm                398 non-null object
cad               398 non-null object
appet             399 non-null object
pe         

In [5]:
dataset.isnull().any()

id                False
age                True
bp                 True
sg                 True
al                 True
su                 True
rbc                True
pc                 True
pcc                True
ba                 True
bgr                True
bu                 True
sc                 True
sod                True
pot                True
hemo               True
pcv                True
wc                 True
rc                 True
htn                True
dm                 True
cad                True
appet              True
pe                 True
ane                True
classification    False
dtype: bool

In [6]:
dataset.isnull().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [7]:
dataset["classification"].unique()

array(['ckd', 'ckd\t', 'notckd'], dtype=object)

In [8]:
dataset["pcv"].unique()

array(['44', '38', '31', '32', '35', '39', '36', '33', '29', '28', nan,
       '16', '24', '37', '30', '34', '40', '45', '27', '48', '\t?', '52',
       '14', '22', '18', '42', '17', '46', '23', '19', '25', '41', '26',
       '15', '21', '43', '20', '\t43', '47', '9', '49', '50', '53', '51',
       '54'], dtype=object)

In [9]:
dataset["wc"].unique()

array(['7800', '6000', '7500', '6700', '7300', nan, '6900', '9600',
       '12100', '4500', '12200', '11000', '3800', '11400', '5300', '9200',
       '6200', '8300', '8400', '10300', '9800', '9100', '7900', '6400',
       '8600', '18900', '21600', '4300', '8500', '11300', '7200', '7700',
       '14600', '6300', '\t6200', '7100', '11800', '9400', '5500', '5800',
       '13200', '12500', '5600', '7000', '11900', '10400', '10700',
       '12700', '6800', '6500', '13600', '10200', '9000', '14900', '8200',
       '15200', '5000', '16300', '12400', '\t8400', '10500', '4200',
       '4700', '10900', '8100', '9500', '2200', '12800', '11200', '19100',
       '\t?', '12300', '16700', '2600', '26400', '8800', '7400', '4900',
       '8000', '12000', '15700', '4100', '5700', '11500', '5400', '10800',
       '9900', '5200', '5900', '9300', '9700', '5100', '6600'],
      dtype=object)

In [10]:
dataset["rc"].unique()

array(['5.2', nan, '3.9', '4.6', '4.4', '5', '4.0', '3.7', '3.8', '3.4',
       '2.6', '2.8', '4.3', '3.2', '3.6', '4', '4.1', '4.9', '2.5', '4.2',
       '4.5', '3.1', '4.7', '3.5', '6.0', '5.0', '2.1', '5.6', '2.3',
       '2.9', '2.7', '8.0', '3.3', '3.0', '3', '2.4', '4.8', '\t?', '5.4',
       '6.1', '6.2', '6.3', '5.1', '5.8', '5.5', '5.3', '6.4', '5.7',
       '5.9', '6.5'], dtype=object)

In [11]:
dataset['pcv']=dataset['pcv'].replace("\t43","43")
dataset['wc']=dataset['wc'].replace("\t6200","6200")
dataset['wc']=dataset['wc'].replace("\t8400","8400")
dataset['classification']=dataset['classification'].replace("ckd\t","ckd")
dataset['rc'] = dataset['rc'].replace(to_replace = "\t?",value = np.nan)
dataset['wc'] = dataset['wc'].replace(to_replace = "\t?",value = np.nan)
dataset['pcv'] = dataset['pcv'].replace(to_replace = "\t?",value = np.nan)


In [12]:
dataset["pcv"].unique()

array(['44', '38', '31', '32', '35', '39', '36', '33', '29', '28', nan,
       '16', '24', '37', '30', '34', '40', '45', '27', '48', '52', '14',
       '22', '18', '42', '17', '46', '23', '19', '25', '41', '26', '15',
       '21', '43', '20', '47', '9', '49', '50', '53', '51', '54'],
      dtype=object)

In [13]:
dataset["rc"].unique()

array(['5.2', nan, '3.9', '4.6', '4.4', '5', '4.0', '3.7', '3.8', '3.4',
       '2.6', '2.8', '4.3', '3.2', '3.6', '4', '4.1', '4.9', '2.5', '4.2',
       '4.5', '3.1', '4.7', '3.5', '6.0', '5.0', '2.1', '5.6', '2.3',
       '2.9', '2.7', '8.0', '3.3', '3.0', '3', '2.4', '4.8', '5.4', '6.1',
       '6.2', '6.3', '5.1', '5.8', '5.5', '5.3', '6.4', '5.7', '5.9',
       '6.5'], dtype=object)

In [14]:
dataset["classification"].unique()

array(['ckd', 'notckd'], dtype=object)

In [15]:
dataset["wc"].unique()

array(['7800', '6000', '7500', '6700', '7300', nan, '6900', '9600',
       '12100', '4500', '12200', '11000', '3800', '11400', '5300', '9200',
       '6200', '8300', '8400', '10300', '9800', '9100', '7900', '6400',
       '8600', '18900', '21600', '4300', '8500', '11300', '7200', '7700',
       '14600', '6300', '7100', '11800', '9400', '5500', '5800', '13200',
       '12500', '5600', '7000', '11900', '10400', '10700', '12700',
       '6800', '6500', '13600', '10200', '9000', '14900', '8200', '15200',
       '5000', '16300', '12400', '10500', '4200', '4700', '10900', '8100',
       '9500', '2200', '12800', '11200', '19100', '12300', '16700',
       '2600', '26400', '8800', '7400', '4900', '8000', '12000', '15700',
       '4100', '5700', '11500', '5400', '10800', '9900', '5200', '5900',
       '9300', '9700', '5100', '6600'], dtype=object)

In [16]:
dataset["appet"].unique()

array(['good', 'poor', nan], dtype=object)

In [17]:
dataset["age"].fillna(dataset["age"].mean(),inplace = True)
dataset["bp"].fillna(dataset["bp"].mean(),inplace = True)
dataset["sg"].fillna(dataset["sg"].mean(),inplace = True)
dataset["al"].fillna(dataset["al"].mean(),inplace = True)
dataset["su"].fillna(dataset["su"].mean(),inplace = True)
dataset["bgr"].fillna(dataset["bgr"].mean(),inplace = True)
dataset["bu"].fillna(dataset["bu"].mean(),inplace = True)
dataset["sc"].fillna(dataset["sc"].mean(),inplace = True)
dataset["sod"].fillna(dataset["sod"].mean(),inplace = True)
dataset["pot"].fillna(dataset["pot"].mean(),inplace = True)
dataset["hemo"].fillna(dataset["hemo"].mean(),inplace = True)

In [18]:
dataset["rbc"].fillna(dataset["rbc"].mode()[0],inplace =True)
dataset["pcc"].fillna(dataset["pcc"].mode()[0],inplace =True)
dataset["pc"].fillna(dataset["pc"].mode()[0],inplace =True)
dataset["ba"].fillna(dataset["ba"].mode()[0],inplace =True)
dataset["dm"].fillna(dataset["dm"].mode()[0],inplace =True)
dataset["cad"].fillna(dataset["cad"].mode()[0],inplace =True)
dataset["appet"].fillna(dataset["appet"].mode()[0],inplace =True)
dataset["pe"].fillna(dataset["pe"].mode()[0],inplace =True)
dataset["ane"].fillna(dataset["ane"].mode()[0],inplace =True)
dataset["htn"].fillna(dataset["htn"].mode()[0],inplace =True)
dataset['pcv']=dataset['pcv'].replace(to_replace = np.nan,value = dataset.pcv.mode()[0])
dataset['wc']=dataset['wc'].replace(to_replace = np.nan,value = dataset.wc.mode()[0])
dataset['rc']=dataset['rc'].replace(to_replace = np.nan,value = dataset.rc.mode()[0])

In [19]:
dataset.isnull().sum()

id                0
age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hemo              0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [20]:
le=LabelEncoder()
dataset["rbc"] = le.fit_transform(dataset["rbc"])
dataset["pcc"] = le.fit_transform(dataset["pcc"])
dataset["pc"] = le.fit_transform(dataset["pc"])
dataset["ba"] = le.fit_transform(dataset["ba"])
dataset["cad"] = le.fit_transform(dataset["cad"])
dataset["dm"] = le.fit_transform(dataset["dm"])
dataset["appet"] = le.fit_transform(dataset["appet"])
dataset["pe"] = le.fit_transform(dataset["pe"])
dataset["ane"] = le.fit_transform(dataset["ane"])
dataset["htn"] = le.fit_transform(dataset["htn"])
dataset["classification"] = le.fit_transform(dataset["classification"])

In [21]:
dataset.head()

id   age    bp     sg   al   su  rbc  pc  pcc  ba  ...  pcv    wc   rc  \
0   0  48.0  80.0  1.020  1.0  0.0    1   1    0   0  ...   44  7800  5.2   
1   1   7.0  50.0  1.020  4.0  0.0    1   1    0   0  ...   38  6000  5.2   
2   2  62.0  80.0  1.010  2.0  3.0    1   1    0   0  ...   31  7500  5.2   
3   3  48.0  70.0  1.005  4.0  0.0    1   0    1   0  ...   32  6700  3.9   
4   4  51.0  80.0  1.010  2.0  0.0    1   1    0   0  ...   35  7300  4.6   

   htn  dm  cad appet pe ane  classification  
0    1   4    1     0  0   0               0  
1    0   3    1     0  0   0               0  
2    0   4    1     1  0   1               0  
3    1   3    1     1  1   1               0  
4    0   3    1     0  0   0               0  

[5 rows x 26 columns]

In [22]:
dataset.columns

Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr',
       'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [23]:
dataset.columns=['id','age','blood_pressure','specific_gravity','albumin',
              'sugar','red_blood_cells','pus_cell','pus_cell_clumps','bacteria',
              'blood glucose random','blood_urea','serum_creatinine','sodium','potassium',
              'hemoglobin','packed_cell_volume','white_blood_cell_count','red_blood_cell_count',
              'hypertension','diabetesmellitus','coronary_artery_disease','appetite',
              'pedal_edema','anemia','class']

In [24]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
id                         400 non-null int64
age                        400 non-null float64
blood_pressure             400 non-null float64
specific_gravity           400 non-null float64
albumin                    400 non-null float64
sugar                      400 non-null float64
red_blood_cells            400 non-null int32
pus_cell                   400 non-null int32
pus_cell_clumps            400 non-null int32
bacteria                   400 non-null int32
blood glucose random       400 non-null float64
blood_urea                 400 non-null float64
serum_creatinine           400 non-null float64
sodium                     400 non-null float64
potassium                  400 non-null float64
hemoglobin                 400 non-null float64
packed_cell_volume         400 non-null object
white_blood_cell_count     400 non-null object
red_blood_cell_count       400 non-null obj

In [25]:
dataset = dataset.drop(["id"],axis=1)

In [26]:
dataset.head(1)

age  blood_pressure  specific_gravity  albumin  sugar  red_blood_cells  \
0  48.0            80.0              1.02      1.0    0.0                1   

   pus_cell  pus_cell_clumps  bacteria  blood glucose random  ...  \
0         1                0         0                 121.0  ...   

   packed_cell_volume  white_blood_cell_count  red_blood_cell_count  \
0                  44                    7800                   5.2   

   hypertension  diabetesmellitus coronary_artery_disease appetite  \
0             1                 4                       1        0   

  pedal_edema  anemia  class  
0           0       0      0  

[1 rows x 25 columns]

In [27]:
x = dataset.iloc[:,0:24].values
y = dataset.iloc[:,24].values

In [28]:
x

array([[48.0, 80.0, 1.02, ..., 0, 0, 0],
       [7.0, 50.0, 1.02, ..., 0, 0, 0],
       [62.0, 80.0, 1.01, ..., 1, 0, 1],
       ...,
       [12.0, 80.0, 1.02, ..., 0, 0, 0],
       [17.0, 60.0, 1.025, ..., 0, 0, 0],
       [58.0, 80.0, 1.025, ..., 0, 0, 0]], dtype=object)

In [29]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [31]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [32]:
from sklearn.linear_model import LogisticRegression
lgr = LogisticRegression()
lgr.fit(x_train,y_train)

C:\Users\ram krishna\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [33]:
y_pred = lgr.predict(x_test)

In [34]:
y_pred

array([0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1])

In [35]:
from sklearn.metrics import accuracy_score

In [36]:
accuracy_score(y_pred,y_test)

0.9625

In [37]:
from sklearn.metrics import confusion_matrix

In [38]:
conf_mat = confusion_matrix(y_test,y_pred)
conf_mat

array([[49,  3],
       [ 0, 28]], dtype=int64)

In [39]:
import pickle 

In [40]:
pickle.dump(lgr, open('ckd.pkl','wb'))